image: node:latest

pages:
  stage: deploy
  script:
  - npm install
  - npm run package
  - mkdir public
  - cp index.html nodysseus.bundle.js public/
  artifacts:
    paths:
    - public
  only:
  - main
