image: node:latest

pages:
  stage: deploy
  script:
  - npm install
  - npm run package
  - mkdir public
  - cp index.html nodysseus.bundle.js sw.js nodysseus.webmanifest public/
  - cp -R json/ public
  artifacts:
    paths:
    - public
  only:
  - main
